<h1>thunky</h1>

<p>Delay the evaluation of a paramless async function and cache the result (see <a href="http://en.wikipedia.org/wiki/Thunk_%28functional_programming%29">thunk</a>).</p>

<pre><code>npm install thunky
</code></pre>

<h2>Example</h2>

<p>Let’s make a simple function that returns a random number 1 second after it is called for the first time</p>

<p>``` js
var thunky = require(‘thunky’);</p>

<p>var test = thunky(function(callback) { // the inner function should only accept a callback
	console.log(‘waiting 1s and returning random number’);
	setTimeout(function() {
		callback(Math.random());
	}, 1000);
});</p>

<p>test(function(num) {  // inner function is called the first time we call test
	console.log(num); // prints random number
});</p>

<p>test(function(num) {  // subsequent calls waits for the first call to finish and return the same value
	console.log(num); // prints the same random number as above
});
```</p>

<h2>Lazy evaluation</h2>

<p>Thunky makes it easy to implement a lazy evaluation pattern.</p>

<p>``` js
var getDb = thunky(function(callback) {
	db.open(myConnectionString, callback);
});</p>

<p>var queryDb = function(query, callback) {
	getDb(function(err, db) {
		if (err) return callback(err);
		db.query(query, callback);
	});
};</p>

<p>queryDb(‘some query’, function(err, result) { … } );</p>

<p>queryDb(‘some other query’, function(err, result) { … } );
```</p>

<p>The first time <code>getDb</code> is called it will try do open a connection to the database.
Any subsequent calls will just wait for the first call to complete and then call your callback.</p>

<p>A nice property of this pattern is that it <em>easily</em> allows us to pass any error caused by <code>getDb</code> to the <code>queryDb</code> callback.</p>

<h2>Error → No caching</h2>

<p>If the thunk callback is called with an <code>Error</code> object as the first argument it will not cache the result</p>

<p>``` js
var fails = thunky(function(callback) {
	console.log(‘returning an error’);
	callback(new Error(‘bad stuff’));
});</p>

<p>fails(function(err) { // inner function is called
	console.log(err);
});</p>

<p>fails(function(err) { // inner function is called again as it returned an error before
	console.log(err);
});
```</p>

<h2>License</h2>

<p>MIT</p>